AllCops:
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Style/Documentation:
  # Skips checking to make sure top level modules / classes have a comment.
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - "**/*.gemspec"

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
